sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  allow_failures:
    - python: "3.2"
install:
  - pip install pep8
  - pip install -r requirements.txt
script:
  - nosetests -v
  - pep8 --ignore=E501 ./cfgdiff .
  - ./cfgdiff -v
  - ./cfgdiff -h
  - ./cfgdiff -i ini ./test/test_same_1-a.ini ./test/test_same_1-b.ini
  - ./cfgdiff -i json ./test/test_same_1-a.json ./test/test_same_1-b.json
